# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)

1.21.5


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
print(np.zeros(10,dtype = np.int8))

[0 0 0 0 0 0 0 0 0 0]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [9]:
print(np.size(np.zeros(10,dtype = np.int8)))

10


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [12]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [13]:
a = np.zeros(10,dtype = np.int8)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [17]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [18]:
print(b[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [19]:
b = np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [26]:
a = [1,2,0,0,4,0]
type(np.nonzero(a))
b = []
for i in np.nonzero(a):
    b.append(i)
b

[array([0, 1, 4], dtype=int64)]

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [30]:
a = np.eye(3,dtype = np.int8)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [31]:
print(np.random.rand(3,3,3))

[[[0.32466511 0.49535712 0.66910403]
  [0.37015793 0.99384025 0.12181285]
  [0.05470761 0.20578425 0.88527915]]

 [[0.42658059 0.93616901 0.01250904]
  [0.45404998 0.64616659 0.27012321]
  [0.65547255 0.77825199 0.03672465]]

 [[0.15787078 0.80943349 0.90866827]
  [0.32171915 0.48146135 0.26502832]
  [0.8677986  0.01999117 0.08141439]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [33]:
a = np.random.rand(10,10)
maxi = np.max(a)
mini = np.min(a)
print(maxi,mini)

0.9773670335083783 0.0010326561505505927


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [34]:
a = np.random.rand(30)
print(np.mean(a))

0.5229988858060811


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [38]:
a = np.zeros(16,dtype = np.int8).reshape(4,4)
a[1:-1,1:-1] = 1
print(a)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [42]:
a = np.ones(16,dtype = np.int8).reshape(4,4)
print(np.pad(a,1,mode = 'constant'))

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [43]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [45]:
a = [1,2,3,4]
print(np.diag(a,-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [53]:
a = np.zeros(64,dtype = np.int8).reshape(8,8)
a[::2,1::2] = 1
a[1::2,::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [54]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [6]:
import numpy as np
a = (1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1)
print(np.tile(a,4).reshape(8,8))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [7]:
a = np.random.rand(5,5)
mini = np.min(a)
maxi = np.max(a)
print((a - mini)/(maxi-mini))

[[0.46033444 0.31881573 0.22688993 0.         0.64001864]
 [0.06589873 0.19291599 0.19346691 0.91754432 0.25985757]
 [0.60770809 0.97005192 0.03866168 1.         0.51631853]
 [0.44641178 0.44211862 0.56414046 0.57939682 0.16894665]
 [0.47284573 0.50897358 0.62749375 0.12872404 0.52093245]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [8]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)


1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [10]:
m1 = np.random.rand(5,3)
m2 = np.random.rand(3,2)
print(np.dot(m1,m2))

[[0.13442519 0.24035446]
 [0.50497782 1.12941765]
 [0.54813777 1.21446828]
 [0.1047695  0.55487366]
 [0.38244215 0.87700021]]
[[0.13442519 0.24035446]
 [0.50497782 1.12941765]
 [0.54813777 1.21446828]
 [0.1047695  0.55487366]
 [0.38244215 0.87700021]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [16]:
a = np.arange(16)
"""
m = (a>3) & (a<8)
a[m] = a[m] * -1
print(a)
"""
for i in a:
    if a[i]>3 and a[i]<8:
        a[i] = a[i] * -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [17]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)


Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [21]:
"""
Except last expression (Z<Z>Z) all are legal
"""

'\nExcept last expression (Z<Z>Z) all are legal\n'

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [28]:
a = np.random.rand(5,5)
a = np.round(a,2)
a

array([[0.5 , 0.19, 0.12, 0.2 , 0.21],
       [0.77, 0.71, 0.65, 0.5 , 0.04],
       [0.84, 0.27, 0.86, 0.16, 0.55],
       [0.38, 0.28, 0.28, 0.79, 0.22],
       [0.61, 0.57, 0.19, 0.94, 0.03]])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [2]:
import numpy as np
ar1 = np.array([0,1,2,3,4])
ar2 = [1,3,4]
print(np.intersect1d(ar1,ar2))

[1 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [11]:
with np.errstate(divide = 'ignore'):
    Z = np.ones(1)/0
Z

array([inf])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [12]:
np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [13]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2022-07-02 2022-07-03 2022-07-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [14]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [15]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [16]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[2. 1. 5. 0. 6. 7. 0. 9. 5. 3.]
[2. 1. 5. 0. 6. 7. 0. 9. 5. 3.]
[2. 1. 5. 0. 6. 7. 0. 9. 5. 3.]
[2 1 5 0 6 7 0 9 5 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [21]:
Z = np.random.rand(5,5)
Z = Z + np.arange(5)
Z

array([[0.13789025, 1.60990666, 2.43451832, 3.96604137, 4.12315701],
       [0.73708058, 1.82522092, 2.25701944, 3.81507389, 4.21852333],
       [0.78410593, 1.97626554, 2.01601584, 3.54058989, 4.69678954],
       [0.10514214, 1.26865003, 2.39686051, 3.65203275, 4.9827056 ],
       [0.96755815, 1.56683094, 2.03072558, 3.9450176 , 4.52440445]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [26]:
def numpy_array():
    for x in range(10):
        yield x
Z = np.fromiter(numpy_array(),dtype = np.int8,count =-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [33]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [35]:
z = np.random.rand(10)
z.sort()
print(z)

[0.18262174 0.24547046 0.27752591 0.44866553 0.49385824 0.69151491
 0.77771795 0.79666524 0.96113263 0.96513288]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [36]:
import numpy as np
import functools as ft
Z = np.arange(10)
ft.reduce(np.add,Z,0)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [38]:
A = np.random.rand(2,2)
B = np.random.rand(2,2)
equal = np.allclose(A,B)
print(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

[[0.30976657 0.87009571]
 [0.82370184 0.51933356]] [[0.07486889 0.77296093]
 [0.27140964 0.45275274]]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [39]:
a = np.ones(9).reshape(3,3)
a.flags.writeable = False
a[1] = 0

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [40]:
import numpy as np
z= np.random.randint(0,9,(10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[8.06225775 1.05165021]
 [6.40312424 0.67474094]
 [4.12310563 1.32581766]
 [9.89949494 0.78539816]
 [5.38516481 0.38050638]
 [7.         0.        ]
 [0.         0.        ]
 [7.07106781 0.78539816]
 [4.         1.57079633]
 [7.07106781 0.78539816]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [41]:
a = np.random.rand(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.99321792 0.24783043 0.29437989 0.41148267 0.34724992 0.34683365
 0.89580989 0.17277473 0.23217892 0.52376416]
[0.         0.24783043 0.29437989 0.41148267 0.34724992 0.34683365
 0.89580989 0.17277473 0.23217892 0.52376416]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [42]:
Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
#print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
#print(X)
X  = np.tile(X,(10,1)).T
#print(X)

C = 1/(X - Y)
C

array([[0.16666667, 0.33333333, 0.14285714, 0.125     , 0.25      ,
        0.2       , 0.1       , 0.25      , 0.5       , 0.16666667],
       [0.07692308, 0.1       , 0.07142857, 0.06666667, 0.09090909,
        0.08333333, 0.05882353, 0.09090909, 0.11111111, 0.07692308],
       [0.0625    , 0.07692308, 0.05882353, 0.05555556, 0.07142857,
        0.06666667, 0.05      , 0.07142857, 0.08333333, 0.0625    ],
       [0.16666667, 0.33333333, 0.14285714, 0.125     , 0.25      ,
        0.2       , 0.1       , 0.25      , 0.5       , 0.16666667],
       [0.08333333, 0.11111111, 0.07692308, 0.07142857, 0.1       ,
        0.09090909, 0.0625    , 0.1       , 0.125     , 0.08333333],
       [0.16666667, 0.33333333, 0.14285714, 0.125     , 0.25      ,
        0.2       , 0.1       , 0.25      , 0.5       , 0.16666667],
       [0.0625    , 0.07692308, 0.05882353, 0.05555556, 0.07142857,
        0.06666667, 0.05      , 0.07142857, 0.08333333, 0.0625    ],
       [0.14285714, 0.25      , 0.125    

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [43]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [45]:
a = np.random.rand(5,5)
for i in a:
    print(i)

[0.31025236 0.50635453 0.06796381 0.98114022 0.85911791]
[0.92796329 0.44890343 0.61964084 0.67464846 0.67867011]
[0.03469228 0.07379012 0.68900328 0.03163398 0.5006475 ]
[0.14076485 0.9887515  0.58159312 0.52760328 0.46971873]
[0.66559777 0.1956724  0.1539886  0.70153346 0.31768512]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [46]:
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[5.96086634 9.91137399 3.63610159 6.97518336 5.79994726 1.82427879
 0.85505806 5.49651079 0.27566487 5.29065931]
************************************************************
5.290659306637596


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [47]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [48]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.26022141 0.70996682 0.66169343 0.86032125 0.96243405
  0.96889994 0.18020019 0.75482575 1.01784665]
 [0.26022141 0.         0.85960133 0.41368655 0.6236707  0.76602986
  0.75285313 0.08063734 0.50733418 0.88785442]
 [0.70996682 0.85960133 0.         1.07451791 1.17324117 1.10595035
  1.17677663 0.81402169 1.14075591 0.9454486 ]
 [0.66169343 0.41368655 1.07451791 0.         0.21822206 0.42611239
  0.3755203  0.4915181  0.09369164 0.66075555]
 [0.86032125 0.6236707  1.17324117 0.21822206 0.         0.25766222
  0.17516014 0.69848049 0.13540874 0.55102174]
 [0.96243405 0.76602986 1.10595035 0.42611239 0.25766222 0.
  0.10639159 0.82846313 0.37334853 0.31184803]
 [0.96889994 0.75285313 1.17677663 0.3755203  0.17516014 0.10639159
  0.         0.82154111 0.30581895 0.41821176]
 [0.18020019 0.08063734 0.81402169 0.4915181  0.69848049 0.82846313
  0.82154111 0.         0.58520327 0.92941461]
 [0.75482575 0.50733418 1.14075591 0.09369164 0.13540874 0.37334853
  0.30581895 0.58520

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [49]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [50]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])
    

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [51]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [55]:
Z = np.zeros((n,n))
np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [56]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [57]:
Z = np.random.randint(0,10,(5,5))
print(Z)


# Z_1 = Z
# for ind in range(5):
#     Z_1[:,ind].sort()
#print(Z_1)


print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[5 9 2 5 5]
 [4 1 7 7 4]
 [7 9 7 5 1]
 [7 8 6 2 8]
 [9 8 3 6 3]]
[[5 9 2 5 5]
 [7 9 7 5 1]
 [7 8 6 2 8]
 [9 8 3 6 3]
 [4 1 7 7 4]]
[[9 5 5 2 5]
 [1 4 4 7 7]
 [9 7 1 7 5]
 [8 7 8 6 2]
 [8 9 3 3 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [58]:
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

[[ True False  True  True False  True False  True  True  True]
 [ True False False False False False  True False  True  True]
 [False False False  True  True False  True  True  True  True]]
[[False  True False False  True False  True False False False]
 [False  True  True  True  True  True False  True False False]
 [ True  True  True False False  True False False False False]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [59]:
arr = np.array([8, 7, 1, 5, 3, 4])
x = 2
difference_array = np.absolute(arr-x)
index = difference_array.argmin()
print(arr[index])

1


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [60]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [61]:
class NumpyArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NumpyArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [62]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 2. 3. 6. 2. 3. 3. 2. 4. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [63]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [64]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [65]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[61 56 63 47]
 [58 47 55 49]
 [79 62 66 48]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [66]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.51566164 0.57412174 0.55137549 0.37987579 0.29868585 0.3241332
 0.5124009  0.45271113 0.50737917 0.3947762 ]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [67]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.80289566, 0.79843307, 1.60217134, 1.72450446, 1.41996122])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [68]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [69]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [70]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [71]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 32) ( 0, 51) ( 7, 10) ( 7, 13) ( 9, 68) ( 9, 71) (10, 13) (10, 62)
 (10, 82) (12, 28) (12, 48) (15, 64) (15, 65) (21, 35) (21, 97) (28, 48)
 (32, 51) (35, 97) (39, 59) (39, 90) (49, 77) (49, 93) (59, 90) (62, 82)
 (64, 65) (64, 77) (65, 77) (68, 71) (77, 93)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [72]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [73]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [74]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [75]:

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.31782521, -0.94584855,  0.47558274, -0.75406661, -0.0323299 ,
       -0.60747833,  0.65856121,  0.1427527 ,  0.18899159, -0.73162757,
       -0.33341982, -0.53312316,  0.34676692,  0.4365654 ,  0.99108396,
        0.99631708, -0.75936637,  0.92686839, -0.24961229,  0.03032251,
       -0.57378443,  0.75581671, -0.88837852,  0.07652363, -0.64785125,
       -0.69153068,  0.30282016, -0.42735497,  0.15074651,  0.04497909,
       -0.99157581, -0.19686448, -0.57338496, -0.51401772,  0.60091296,
       -0.07090203,  0.44275512,  0.84489291,  0.43640792, -0.14348915,
       -0.36139423, -0.69755424, -0.50678785,  0.71164926,  0.47495595,
        0.91719558,  0.99973309,  0.3239201 ,  0.1756108 , -0.67751273,
        0.74615555,  0.01375449, -0.00169842,  0.8927093 , -0.9666636 ,
       -0.80930479,  0.95086496,  0.39454335, -0.33625825, -0.19884705,
       -0.81844303,  0.44922486, -0.38709835, -0.27143219,  0.61391597,
       -0.03512825, -0.62884594, -0.23280411,  0.53231187,  0.19

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [76]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[4.30034423 3.37043447 3.40111719 2.04121431 2.9243572  4.6918605
 0.95171978 5.11567748 7.2951793  3.14651255]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [77]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [78]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [79]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [80]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[3 0 0]
   [4 1 3]
   [0 4 3]]

  [[0 0 2]
   [1 3 1]
   [4 3 1]]

  [[0 2 2]
   [3 1 1]
   [3 1 2]]

  [[2 2 1]
   [1 1 0]
   [1 2 1]]

  [[2 1 0]
   [1 0 0]
   [2 1 3]]

  [[1 0 4]
   [0 0 3]
   [1 3 2]]

  [[0 4 3]
   [0 3 0]
   [3 2 3]]

  [[4 3 1]
   [3 0 0]
   [2 3 4]]]


 [[[4 1 3]
   [0 4 3]
   [1 2 2]]

  [[1 3 1]
   [4 3 1]
   [2 2 0]]

  [[3 1 1]
   [3 1 2]
   [2 0 2]]

  [[1 1 0]
   [1 2 1]
   [0 2 0]]

  [[1 0 0]
   [2 1 3]
   [2 0 4]]

  [[0 0 3]
   [1 3 2]
   [0 4 1]]

  [[0 3 0]
   [3 2 3]
   [4 1 4]]

  [[3 0 0]
   [2 3 4]
   [1 4 2]]]


 [[[0 4 3]
   [1 2 2]
   [3 0 0]]

  [[4 3 1]
   [2 2 0]
   [0 0 2]]

  [[3 1 2]
   [2 0 2]
   [0 2 0]]

  [[1 2 1]
   [0 2 0]
   [2 0 3]]

  [[2 1 3]
   [2 0 4]
   [0 3 0]]

  [[1 3 2]
   [0 4 1]
   [3 0 2]]

  [[3 2 3]
   [4 1 4]
   [0 2 0]]

  [[2 3 4]
   [1 4 2]
   [2 0 1]]]


 [[[1 2 2]
   [3 0 0]
   [3 2 4]]

  [[2 2 0]
   [0 0 2]
   [2 4 3]]

  [[2 0 2]
   [0 2 0]
   [4 3 3]]

  [[0 2 0]
   [2 0 3]
   [3 3 3]]

  [[2 0 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [81]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [82]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [83]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [84]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [85]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [86]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [87]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [88]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


1.78 s ± 28.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
404 ms ± 25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
213 ms ± 20.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [89]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [90]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 1 0]
 [0 4 4]
 [2 0 0]
 [0 1 3]
 [0 3 1]
 [0 1 1]
 [0 4 0]
 [1 0 0]
 [3 1 1]
 [1 2 3]]
[[2 1 0]
 [0 4 4]
 [2 0 0]
 [0 1 3]
 [0 3 1]
 [0 1 1]
 [0 4 0]
 [1 0 0]
 [3 1 1]
 [1 2 3]]
[[2 1 0]
 [0 4 4]
 [2 0 0]
 [0 1 3]
 [0 3 1]
 [0 1 1]
 [0 4 0]
 [1 0 0]
 [3 1 1]
 [1 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [91]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [92]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [93]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.20657313, 0.06774657, 0.06956228, 0.01324192, 0.1512713 ,
        0.09507347, 0.22707248, 0.20993353, 0.06034885, 0.11456203],
       [0.05515047, 0.01808684, 0.01857159, 0.0035353 , 0.0403861 ,
        0.02538252, 0.06062334, 0.05604762, 0.01611181, 0.03058553],
       [0.3816272 , 0.12515633, 0.1285107 , 0.02446337, 0.27946152,
        0.17564057, 0.41949809, 0.38783527, 0.11148964, 0.21164411],
       [0.70408486, 0.23090775, 0.23709642, 0.04513381, 0.51559383,
        0.32404888, 0.77395494, 0.71553848, 0.20569332, 0.39047377],
       [0.56957151, 0.1867935 , 0.19179984, 0.03651113, 0.41709113,
        0.26214029, 0.62609312, 0.57883694, 0.16639621, 0.3158749 ],
       [0.72936432, 0.23919826, 0.24560912, 0.0467543 , 0.53410571,
        0.33568353, 0.80174302, 0.74122917, 0.21307853, 0.40449334],
       [0.13641277, 0.04473717, 0.04593619, 0.00874444, 0.09989361,
        0.06278278, 0.14994973, 0.13863184, 0.03985201, 0.07565226],
       [0.40908344, 0.13416073, 0.1377564

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [94]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [95]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [96]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.06887199  0.28795774]
